[features]
resolution = true
skip-lint = false

[programs.localnet]
skillproof = "3zhshhVRmnVyTio5rXHindxv9MGBR3aFtFgWLH7wNi6C"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p skillproof"
